AWSTemplateFormatVersion: 2010-09-09
Description: >-
  user-copy-rds-to-dynamo

Transform:
- AWS::Serverless-2016-10-31

Resources:
  copyUsersRdsToDynamo:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist
      Handler: index.handler
      Runtime: nodejs10.x
      MemorySize: 128
      Timeout: 100
      Description: Get all users from RDS and Copy them into DynamoDB.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SampleTable
      Environment:
        Variables:
          USER_TABLE: !Ref UserTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: GET
